// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP23lO0hoopalhDSGr8P3tK_QiAbzy86Y',
    appId: '1:43081141846:web:dbebac194c892dadf8f5f7',
    messagingSenderId: '43081141846',
    projectId: 'biblioteca-5db63',
    authDomain: 'biblioteca-5db63.firebaseapp.com',
    storageBucket: 'biblioteca-5db63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3wLCrfb-zuDbQ5Cp6qm13xbXteXzNzKs',
    appId: '1:43081141846:android:41582ed6bb16eb1af8f5f7',
    messagingSenderId: '43081141846',
    projectId: 'biblioteca-5db63',
    storageBucket: 'biblioteca-5db63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXOZ1NMiSxC6VF4aDJKD4D3Fc_omRRVrY',
    appId: '1:43081141846:ios:9bf5619cb7e1b148f8f5f7',
    messagingSenderId: '43081141846',
    projectId: 'biblioteca-5db63',
    storageBucket: 'biblioteca-5db63.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXOZ1NMiSxC6VF4aDJKD4D3Fc_omRRVrY',
    appId: '1:43081141846:ios:9bf5619cb7e1b148f8f5f7',
    messagingSenderId: '43081141846',
    projectId: 'biblioteca-5db63',
    storageBucket: 'biblioteca-5db63.firebasestorage.app',
    iosBundleId: 'com.example.biblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP23lO0hoopalhDSGr8P3tK_QiAbzy86Y',
    appId: '1:43081141846:web:d7af8cd6f25ef9cbf8f5f7',
    messagingSenderId: '43081141846',
    projectId: 'biblioteca-5db63',
    authDomain: 'biblioteca-5db63.firebaseapp.com',
    storageBucket: 'biblioteca-5db63.firebasestorage.app',
  );

}